// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  EthereumCall,
  EthereumEvent,
  SmartContract,
  EthereumValue,
  JSONValue,
  TypedMap,
  Entity,
  EthereumTuple,
  Bytes,
  Address,
  BigInt,
  CallResult
} from "@graphprotocol/graph-ts";

export class NewExchange extends EthereumEvent {
  get params(): NewExchange__Params {
    return new NewExchange__Params(this);
  }
}

export class NewExchange__Params {
  _event: NewExchange;

  constructor(event: NewExchange) {
    this._event = event;
  }

  get token(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get exchange(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class Contract extends SmartContract {
  static bind(address: Address): Contract {
    return new Contract("Contract", address);
  }

  createExchange(token: Address): Address {
    let result = super.call("createExchange", [
      EthereumValue.fromAddress(token)
    ]);

    return result[0].toAddress();
  }

  try_createExchange(token: Address): CallResult<Address> {
    let result = super.tryCall("createExchange", [
      EthereumValue.fromAddress(token)
    ]);
    if (result.reverted) {
      return new CallResult();
    }
    let value = result.value;
    return CallResult.fromValue(value[0].toAddress());
  }

  getExchange(token: Address): Address {
    let result = super.call("getExchange", [EthereumValue.fromAddress(token)]);

    return result[0].toAddress();
  }

  try_getExchange(token: Address): CallResult<Address> {
    let result = super.tryCall("getExchange", [
      EthereumValue.fromAddress(token)
    ]);
    if (result.reverted) {
      return new CallResult();
    }
    let value = result.value;
    return CallResult.fromValue(value[0].toAddress());
  }

  getToken(exchange: Address): Address {
    let result = super.call("getToken", [EthereumValue.fromAddress(exchange)]);

    return result[0].toAddress();
  }

  try_getToken(exchange: Address): CallResult<Address> {
    let result = super.tryCall("getToken", [
      EthereumValue.fromAddress(exchange)
    ]);
    if (result.reverted) {
      return new CallResult();
    }
    let value = result.value;
    return CallResult.fromValue(value[0].toAddress());
  }

  getTokenWithId(token_id: BigInt): Address {
    let result = super.call("getTokenWithId", [
      EthereumValue.fromUnsignedBigInt(token_id)
    ]);

    return result[0].toAddress();
  }

  try_getTokenWithId(token_id: BigInt): CallResult<Address> {
    let result = super.tryCall("getTokenWithId", [
      EthereumValue.fromUnsignedBigInt(token_id)
    ]);
    if (result.reverted) {
      return new CallResult();
    }
    let value = result.value;
    return CallResult.fromValue(value[0].toAddress());
  }

  exchangeTemplate(): Address {
    let result = super.call("exchangeTemplate", []);

    return result[0].toAddress();
  }

  try_exchangeTemplate(): CallResult<Address> {
    let result = super.tryCall("exchangeTemplate", []);
    if (result.reverted) {
      return new CallResult();
    }
    let value = result.value;
    return CallResult.fromValue(value[0].toAddress());
  }

  tokenCount(): BigInt {
    let result = super.call("tokenCount", []);

    return result[0].toBigInt();
  }

  try_tokenCount(): CallResult<BigInt> {
    let result = super.tryCall("tokenCount", []);
    if (result.reverted) {
      return new CallResult();
    }
    let value = result.value;
    return CallResult.fromValue(value[0].toBigInt());
  }
}

export class InitializeFactoryCall extends EthereumCall {
  get inputs(): InitializeFactoryCall__Inputs {
    return new InitializeFactoryCall__Inputs(this);
  }

  get outputs(): InitializeFactoryCall__Outputs {
    return new InitializeFactoryCall__Outputs(this);
  }
}

export class InitializeFactoryCall__Inputs {
  _call: InitializeFactoryCall;

  constructor(call: InitializeFactoryCall) {
    this._call = call;
  }

  get template(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class InitializeFactoryCall__Outputs {
  _call: InitializeFactoryCall;

  constructor(call: InitializeFactoryCall) {
    this._call = call;
  }
}

export class CreateExchangeCall extends EthereumCall {
  get inputs(): CreateExchangeCall__Inputs {
    return new CreateExchangeCall__Inputs(this);
  }

  get outputs(): CreateExchangeCall__Outputs {
    return new CreateExchangeCall__Outputs(this);
  }
}

export class CreateExchangeCall__Inputs {
  _call: CreateExchangeCall;

  constructor(call: CreateExchangeCall) {
    this._call = call;
  }

  get token(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class CreateExchangeCall__Outputs {
  _call: CreateExchangeCall;

  constructor(call: CreateExchangeCall) {
    this._call = call;
  }

  get out(): Address {
    return this._call.outputValues[0].value.toAddress();
  }
}
